const KEY_GAMES='kbo-ticket-helper.games.v1';
const KEY_PREFS='kbo-ticket-helper.preferences.v1';
const REMINDERS=[['1일 전',1440],['1시간 전',60],['10분 전',10],['1분 전',1],['정각',0]];
let rules,games=[],prefs={favoriteTeam:'SAMSUNG',defaultPartySize:2,defaultSeatMemo:'1순위: 1루 내야 / 2순위: 중앙 / 3순위: 외야'},timers=[];
const app=document.querySelector('#app');
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
const save=()=>{localStorage.setItem(KEY_GAMES,JSON.stringify(games));localStorage.setItem(KEY_PREFS,JSON.stringify(prefs));};
const getJson=async url=>{const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw new Error(`${url} 파일을 불러오지 못했습니다.`);return r.json();};
const inputDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=(n=0)=>{const d=new Date();d.setDate(d.getDate()+n);return inputDate(d)};
const team=c=>rules?.teams?.[c]||{name:c,shortName:c,stadium:'',ticketUrl:''};
const rule=home=>{const t=team(home),d=rules.defaultRule;return {...d,...t,openOffsetDays:Number(t.openOffsetDays??d.openOffsetDays),openTime:t.openTime||d.openTime,certainty:t.certainty||d.certainty||'estimated'}};
const openAt=g=>{const r=rule(g.home);if(!g.date||!r.openTime)return null;const d=new Date(`${g.date}T${r.openTime}:00+09:00`);d.setDate(d.getDate()-Number(r.openOffsetDays||0));return d};
const fmt=d=>d?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(d):'계산 불가';
const left=d=>{if(!d)return'예매 시각 계산 불가';const diff=d-Date.now(),a=Math.abs(diff),day=Math.floor(a/864e5),h=Math.floor(a%864e5/36e5),m=Math.floor(a%36e5/6e4),s=`${day?day+'일 ':''}${h?h+'시간 ':''}${m}분`;if(diff<=0)return a<18e5?'지금 예매 진입 시간':`오픈 후 ${s} 지남`;return `${s} 남음`;};
const status=d=>{if(!d)return['확인 필요','muted'];const diff=d-Date.now();if(diff<=0&&Math.abs(diff)<18e5)return['예매 진입','live'];if(diff<=0)return['오픈 완료','done'];if(diff<=36e5)return['1시간 이내','soon'];if(diff<=864e5)return['오늘/내일','soon'];return['대기 중','wait'];};
const options=sel=>Object.entries(rules.teams).map(([c,t])=>`<option value="${esc(c)}" ${c===sel?'selected':''}>${esc(t.shortName||t.name)}</option>`).join('');
const urlFor=g=>(g.ticketUrlOverride||'').trim()||rule(g.home).ticketUrl||'https://www.koreabaseball.com/';
const sorted=()=>[...games].sort((a,b)=>(openAt(a)?.getTime()??9e15)-(openAt(b)?.getTime()??9e15));
function render(){const list=sorted(),next=list.find(g=>openAt(g)&&openAt(g).getTime()>Date.now()-18e5);app.innerHTML=`<header class="hero"><p class="eyebrow">KBO 자동 예매가 아닌 안전한 예매 보조</p><h1>정각에 헤매지 않도록<br>예매 준비를 한 화면에.</h1><p>홈팀 기준 예매처, 오픈 예상 시각, 좌석 선호, 인원, 캘린더 알림을 관리합니다. 좌석 자동 선점·결제·대기열 우회 기능은 넣지 않았습니다.</p>${next?focus(next):''}</header><main class="layout"><section class="panel"><p class="eyebrow">관심 경기 추가</p><h2>홈팀 기준으로 예매 시각 계산</h2>${form()}</section><section class="panel"><div class="row"><div><p class="eyebrow">예매 카드</p><h2>${list.length}개 경기</h2></div><button class="ghost" data-action="permission">알림 권한</button></div><div class="notice"><b>중요:</b> 현재 예매 규칙은 보조용 추정값입니다. 구단 공지와 다르면 <code>data/ticket_rules.json</code>을 수정하거나 경기별 예매 URL을 직접 입력하세요.</div><div class="cards">${list.length?list.map(card).join(''):'<p class="empty">아직 등록한 경기가 없습니다.</p>'}</div></section><section class="panel dark"><p class="eyebrow">운영 원칙</p><h2>이 앱이 하지 않는 것</h2><div class="safety"><span>CAPTCHA 우회 없음</span><span>좌석 자동 클릭 없음</span><span>결제 자동화 없음</span><span>반복 요청 없음</span><span>대기열 우회 없음</span><span>계정 공유 없음</span></div></section></main>`;bind();scheduleAll();}
function focus(g){const h=team(g.home),a=team(g.away),d=openAt(g),s=status(d);return`<div class="focus"><div><span class="badge ${s[1]}">${s[0]}</span><h2>${esc(h.shortName)} vs ${esc(a.shortName)}</h2><p>${esc(g.stadium||h.stadium)} · ${esc(g.date)} ${esc(g.time||'')}</p></div><div class="time"><span>${fmt(d)}</span><strong>${left(d)}</strong></div></div>`}
function form(){return`<form id="game-form" class="game-form"><label>경기일<input type="date" name="date" value="${today(8)}" required></label><label>경기 시간<input type="time" name="time" value="18:30" required></label><label>홈팀<select name="home">${options(prefs.favoriteTeam)}</select></label><label>원정팀<select name="away">${options('KIA')}</select></label><label>경기장<input name="stadium" placeholder="홈팀 기본 경기장 사용"></label><label>인원<input type="number" name="partySize" min="1" max="10" value="${prefs.defaultPartySize}"></label><label class="wide">좌석 선호 메모<input name="seatMemo" value="${esc(prefs.defaultSeatMemo)}"></label><label class="wide">경기별 예매 URL 직접 입력<input type="url" name="ticketUrlOverride" placeholder="정확한 링크를 알고 있으면 붙여넣기"></label><button class="primary wide">관심 경기 추가</button></form>`}
function card(g){const h=team(g.home),a=team(g.away),r=rule(g.home),d=openAt(g),s=status(d);return`<article class="card"><div class="cardTop"><div><span class="badge ${s[1]}">${s[0]}</span><h3>${esc(h.shortName)} vs ${esc(a.shortName)}</h3><p>${esc(g.stadium||h.stadium)} · ${esc(g.date)} ${esc(g.time||'')}</p></div><button class="x" data-action="delete" data-id="${esc(g.id)}">×</button></div><dl><div><dt>예매 오픈</dt><dd>${fmt(d)}</dd></div><div><dt>남은 시간</dt><dd>${left(d)}</dd></div><div><dt>예매처</dt><dd>${esc(r.platform||'확인 필요')} · ${r.certainty==='confirmed'?'확정':'추정'}</dd></div><div><dt>인원/좌석</dt><dd>${esc(g.partySize||prefs.defaultPartySize)}명 · ${esc(g.seatMemo||prefs.defaultSeatMemo)}</dd></div></dl><div class="buttons"><a class="primary" href="${esc(urlFor(g))}" target="_blank" rel="noreferrer">예매처 열기</a><button class="secondary" data-action="ics" data-id="${esc(g.id)}">캘린더 추가</button><button class="secondary" data-action="schedule" data-id="${esc(g.id)}">앱 알림 예약</button><button class="ghost" data-action="copy" data-id="${esc(g.id)}">메모 복사</button></div></article>`}
function bind(){document.querySelector('#game-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),home=f.get('home'),away=f.get('away');if(home===away)return toast('홈팀과 원정팀이 같습니다.');const h=team(home),g={id:crypto.randomUUID?.()||`game-${Date.now()}`,date:f.get('date'),time:f.get('time'),home,away,stadium:f.get('stadium')||h.stadium,partySize:Number(f.get('partySize')||2),seatMemo:f.get('seatMemo')||prefs.defaultSeatMemo,ticketUrlOverride:f.get('ticketUrlOverride')||''};prefs.favoriteTeam=home;prefs.defaultPartySize=g.partySize;prefs.defaultSeatMemo=g.seatMemo;games.push(g);save();render();toast('관심 경기를 추가했습니다.');});document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',async e=>{const a=e.currentTarget.dataset.action,id=e.currentTarget.dataset.id,g=games.find(x=>x.id===id);if(a==='permission')await permission();if(a==='delete'&&g){games=games.filter(x=>x.id!==id);save();render();toast('경기를 삭제했습니다.')}if(a==='schedule'&&g){await permission();schedule(g,true)}if(a==='ics'&&g)downloadIcs(g);if(a==='copy'&&g)copyMemo(g);}));}
async function permission(){if(!('Notification'in window))return toast('이 브라우저는 알림을 지원하지 않습니다. 캘린더 기능을 사용하세요.'),false;if(Notification.permission==='granted')return toast('알림 권한이 허용되어 있습니다.'),true;if(Notification.permission==='denied')return toast('브라우저 설정에서 알림 차단을 해제해야 합니다.'),false;const p=await Notification.requestPermission();toast(p==='granted'?'알림 권한이 허용되었습니다.':'알림 권한이 허용되지 않았습니다.');return p==='granted'}
function scheduleAll(){timers.forEach(clearTimeout);timers=[];if(!('Notification'in window)||Notification.permission!=='granted')return;sorted().slice(0,20).forEach(g=>schedule(g,false))}
function schedule(g,show){if(!('Notification'in window)||Notification.permission!=='granted')return show&&toast('알림 권한이 필요합니다.');const d=openAt(g),h=team(g.home),a=team(g.away),made=[];REMINDERS.forEach(([label,min])=>{const delay=d-min*6e4-Date.now();if(delay<=0||delay>21*864e5)return;timers.push(setTimeout(()=>new Notification(`KBO 예매 ${label}: ${h.shortName} vs ${a.shortName}`,{body:`${fmt(d)} 오픈 예상 · ${g.partySize||prefs.defaultPartySize}명 · ${g.seatMemo||prefs.defaultSeatMemo}`,icon:'/icons/icon.svg',tag:`kbo-${g.id}-${min}`}),delay));made.push(label)});if(show)toast(made.length?`${made.join(', ')} 알림을 예약했습니다. 앱이 열려 있어야 작동합니다.`:'예약 가능한 미래 알림이 없습니다. 캘린더 추가를 권장합니다.')}
const icsTime=d=>`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}00`;
const icsEsc=v=>String(v).replaceAll('\\','\\\\').replaceAll(';','\\;').replaceAll(',','\\,').replaceAll('\n','\\n');
function downloadIcs(g){const d=openAt(g);if(!d)return toast('예매 오픈 시각을 계산할 수 없습니다.');const end=new Date(d.getTime()+15*6e4),h=team(g.home),a=team(g.away),summary=`KBO 예매 시작: ${h.shortName} vs ${a.shortName}`,desc=[`예매처: ${urlFor(g)}`,`인원: ${g.partySize||prefs.defaultPartySize}명`,`좌석 선호: ${g.seatMemo||prefs.defaultSeatMemo}`,'주의: 자동 예매가 아니라 정시 진입 보조 알림입니다.'].join('\n'),ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//KBO Ticket Helper//KO','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${g.id}@kbo-ticket-helper`,`DTSTAMP:${icsTime(new Date())}`,`DTSTART;TZID=Asia/Seoul:${icsTime(d)}`,`DTEND;TZID=Asia/Seoul:${icsTime(end)}`,`SUMMARY:${icsEsc(summary)}`,`LOCATION:${icsEsc(g.stadium||h.stadium)}`,`DESCRIPTION:${icsEsc(desc)}`,`URL:${icsEsc(urlFor(g))}`,'BEGIN:VALARM','TRIGGER:-PT1H','ACTION:DISPLAY',`DESCRIPTION:${icsEsc(summary+' 1시간 전')}`,'END:VALARM','BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY',`DESCRIPTION:${icsEsc(summary+' 10분 전')}`,'END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),u=URL.createObjectURL(blob),aTag=document.createElement('a');aTag.href=u;aTag.download=`kbo-ticket-${g.date}-${h.shortName}-vs-${a.shortName}.ics`;aTag.click();URL.revokeObjectURL(u);toast('캘린더 파일을 만들었습니다.')}
async function copyMemo(g){const h=team(g.home),a=team(g.away),memo=[`[KBO 예매 준비] ${h.name} vs ${a.name}`,`경기: ${g.date} ${g.time} / ${g.stadium||h.stadium}`,`예매 오픈 예상: ${fmt(openAt(g))}`,`예매처: ${urlFor(g)}`,`인원: ${g.partySize||prefs.defaultPartySize}명`,`좌석 선호: ${g.seatMemo||prefs.defaultSeatMemo}`,'주의: 좌석 자동 선점/결제 없이 직접 예매'].join('\n');try{await navigator.clipboard.writeText(memo);toast('준비 메모를 복사했습니다.')}catch{toast('복사에 실패했습니다.')}}
function toast(msg){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3200)}
async function init(){try{rules=await getJson('/data/ticket_rules.json');prefs={...prefs,...load(KEY_PREFS,{})};games=load(KEY_GAMES,[]);if(!games.length){games=(await getJson('/data/games.sample.json')).map(g=>({...g,id:g.id||`sample-${Date.now()}`,date:today(8)}));save()}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});render();setInterval(render,60000)}catch(e){app.innerHTML=`<div class="fatal"><h1>앱을 불러오지 못했습니다</h1><p>${esc(e.message)}</p></div>`}}
init();
